### ISSUE TITLE
not found 'https://formit3d.github.io/SharedPluginUtilities/FormItPluginUtils.mod.js' in '/HelloBlockAsync/v22_0/block.js '

### ISSUE THREAD

**Issue by ideook** [FormIt3D/FormItExamplePlugins#43]
not found 'https://formit3d.github.io/SharedPluginUtilities/FormItPluginUtils.mod.js' in '/HelloBlockAsync/v22_0/block.js '

I want using the function of 'FormItPluginUtils.currentUnits'.

**Comment by josh-goldstein-adsk** [comment]
Hi, that currentUnits function isn't really needed. 

Instead, you can use FormIt.StringConversion.LinearValueToString() which will translate a linear value into a string that represents the current FormIt units. 

See more here: https://formit3d.github.io/FormItExamplePlugins/docs/FormItJSAPI/group__mod__jsapi__formit__stringconversion.html#ga2dac3aad9585927c9b3b1ee9920de4b6 

Note also that this repo (FormItExamplePlugins) is no longer used and has been replaced with individual plugin repos which you can find listed at: https://github.com/FormIt3D
